/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pimpinan;


import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import radhasankara.*;

import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import java.util.HashMap;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author Cheria
 */
public class pimpinanForm extends javax.swing.JFrame {
String ID2;
    Connection con;
    Statement st;
    ResultSet rs;
    /**
     * Creates new form adminForm
     */
    public pimpinanForm() {
        
        initComponents();
         setLocationRelativeTo(null);
         setVisible(true);
         setTitle("Menu Pimpinan");
         connect();
         tampildata();
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/radhasankara/icon.png")));
    }
public void setID(String IDpass){
this.ID2=IDpass;
}

        public void connect() {
            try {
            Class.forName("com.mysql.jdbc.Driver");
            con =DriverManager.getConnection("jdbc:mysql://localhost:3306/radhasankara","root","");
            st = con.createStatement();
            }
            catch(ClassNotFoundException | SQLException e) {
                JOptionPane.showMessageDialog(null,"Error conn");  
                System.out.println(e.getMessage());
            }
        }
        
        public void tampildata(){
            try{
                String tahun="";
            connect();
            rs = st.executeQuery("SELECT YEAR(now())");
            cbbulan.removeAllItems();
            while(rs.next()){
            tahun = rs.getString(1);
            }
            cbbulan.addItem("January "+tahun);
            cbbulan.addItem("February "+tahun);
            cbbulan.addItem("March "+tahun);
            cbbulan.addItem("April "+tahun);
            cbbulan.addItem("May "+tahun);
            cbbulan.addItem("June "+tahun);
            cbbulan.addItem("July "+tahun);
            cbbulan.addItem("August "+tahun);
            cbbulan.addItem("September "+tahun);
            cbbulan.addItem("October "+tahun);
            cbbulan.addItem("November "+tahun);
            cbbulan.addItem("December "+tahun);
            
            
        }
                    catch(Exception e){
                e.printStackTrace();
            }
        }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();
        btnchange = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnlapjual = new javax.swing.JButton();
        btnlapbeli = new javax.swing.JButton();
        btnlapkeu = new javax.swing.JButton();
        btnlapinv = new javax.swing.JButton();
        cbbulan = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        btnbs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(400, 570));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/radhasankara/rs_logo.JPG"))); // NOI18N
        jLabel4.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Cambria", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Radha Sankara");
        jLabel3.setOpaque(true);

        btnlogout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/radhasankara/logout.png"))); // NOI18N
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        btnchange.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnchange.setText("Ubah Password");
        btnchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchangeActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Laporan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(360, 320));

        btnlapjual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnlapjual.setText("Laporan Penjualan");
        btnlapjual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlapjualActionPerformed(evt);
            }
        });

        btnlapbeli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnlapbeli.setText("Laporan Pembelian");
        btnlapbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlapbeliActionPerformed(evt);
            }
        });

        btnlapkeu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnlapkeu.setText("Laporan Keuangan");
        btnlapkeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlapkeuActionPerformed(evt);
            }
        });

        btnlapinv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnlapinv.setText("Laporan Inventory");
        btnlapinv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlapinvActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Bulan");

        btnbs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnbs.setText("Laporan Best Seller");
        btnbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnbs, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlapinv, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlapkeu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlapbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlapjual, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbulan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbbulan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnlapjual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnlapbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnlapkeu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnlapinv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnbs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(btnchange, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnchange, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        dispose();
        loginForm loginform = new loginForm();
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchangeActionPerformed
        // TODO add your handling code here:
        changepassForm changepassform = new changepassForm();
        changepassform.setID(ID2);
    }//GEN-LAST:event_btnchangeActionPerformed

    private void btnlapjualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlapjualActionPerformed
        try{
        connect();
        String[] tgl = cbbulan.getSelectedItem().toString().split(" ");
        rs = st.executeQuery("SELECT invoice, nama_customer, alamat, kelurahan, kecamatan, kota, kodepos, nama_barang, jumlah_jual, harga_jual, jumlah_jual * harga_jual, tanggal_jual, MONTHNAME(tanggal_jual), YEAR(tanggal_jual) FROM tblpenjualan j, tblcustomers c, tblinventory i WHERE j.ID_barang = i.ID_barang AND j.ID_customer = c.ID_customer AND status_penjualan = 'Lunas' AND MONTHNAME(tanggal_jual) = '"+tgl[0]+"' AND YEAR(tanggal_jual) = '"+tgl[1]+"' ORDER BY tanggal_jual, invoice");
        JRResultSetDataSource resultSetDataSource = new JRResultSetDataSource(rs);
        
        System.out.println("Filling report...");
        
        JasperFillManager.fillReportToFile("C:\\Users\\Cheria\\Documents\\NetBeansProjects\\RadhaSanakaraApp\\src\\Pimpinan\\LaporanPenjualan.jasper", new HashMap(), resultSetDataSource);
        
        JasperViewer jv = new JasperViewer("C:\\Users\\Cheria\\Documents\\NetBeansProjects\\RadhaSanakaraApp\\src\\Pimpinan\\LaporanPenjualan.jrprint", false, false);  
        jv.setVisible(true);
        System.out.println("Done!");
        

        rs.close();
        st.close();
        con.close();
        }
                catch(SQLException | JRException e){
                e.printStackTrace();
            }
    }//GEN-LAST:event_btnlapjualActionPerformed

    private void btnlapbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlapbeliActionPerformed
        // TODO add your handling code here:
                try{
        connect();
        String[] tgl = cbbulan.getSelectedItem().toString().split(" ");
        rs = st.executeQuery("SELECT nama_barang, jumlah_beli, harga_beli, jumlah_beli * harga_beli, tanggal_beli, MONTHNAME(tanggal_beli) , YEAR(tanggal_beli) FROM tblpembelian b, tblinventory i WHERE b.ID_barang = i.ID_barang AND MONTHNAME(tanggal_beli) = '"+tgl[0]+"' AND YEAR(tanggal_beli) = '"+tgl[1]+"' order by tanggal_beli, ID_pembelian");
        JRResultSetDataSource resultSetDataSource = new JRResultSetDataSource(rs);
        System.out.println("Filling report...");
        JasperFillManager.fillReportToFile("C:\\Users\\Cheria\\Documents\\NetBeansProjects\\RadhaSanakaraApp\\src\\Pimpinan\\LaporanPembelian.jasper", new HashMap(), resultSetDataSource);
        JasperViewer jv = new JasperViewer("C:\\Users\\Cheria\\Documents\\NetBeansProjects\\RadhaSanakaraApp\\src\\Pimpinan\\LaporanPembelian.jrprint", false, false);  
        jv.setVisible(true);
        System.out.println("Done!");
        

        rs.close();
        st.close();
        con.close();
        }
                catch(SQLException | JRException e){
                e.printStackTrace();
            }
    }//GEN-LAST:event_btnlapbeliActionPerformed

    private void btnlapkeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlapkeuActionPerformed
        // TODO add your handling code here:
         try{
        connect();
        rs = st.executeQuery("select YEAR(now()), SUM(jumlah_jual*harga_jual), (select SUM(jumlah_beli*harga_beli)  from tblpembelian), SUM(jumlah_jual*harga_jual)-(select SUM(jumlah_beli*harga_beli)  from tblpembelian) from tblpenjualan where YEAR(tanggal_jual) = YEAR(now()) AND (select YEAR(tanggal_beli) from tblpembelian group by (YEAR(tanggal_beli))) = YEAR(now()) group by YEAR(now())");
        JRResultSetDataSource resultSetDataSource = new JRResultSetDataSource(rs);
        System.out.println("Filling report...");
        JasperFillManager.fillReportToFile("C:\\Users\\Cheria\\Documents\\NetBeansProjects\\RadhaSanakaraApp\\src\\Pimpinan\\LaporanKeuangan.jasper", new HashMap(), resultSetDataSource);
        JasperViewer jv = new JasperViewer("C:\\Users\\Cheria\\Documents\\NetBeansProjects\\RadhaSanakaraApp\\src\\Pimpinan\\LaporanKeuangan.jrprint", false, false);  
        jv.setVisible(true);
        System.out.println("Done!");
        

        rs.close();
        st.close();
        con.close();
        }
                catch(SQLException | JRException e){
                e.printStackTrace();
            }
    }//GEN-LAST:event_btnlapkeuActionPerformed

    private void btnlapinvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlapinvActionPerformed
        // TODO add your handling code here:
                 try{
        connect();
        rs = st.executeQuery("select ID_barang, nama_barang, jenis, merek, tipe, satuan, stock, status_barang, YEAR(now()) from tblinventory i, tbljenis j, tblmerek m, tbltipe t, tblsatuan s where i.ID_tipe = t.ID_tipe AND i.ID_satuan = s.ID_satuan AND j.ID_jenis = t.ID_jenis AND m.ID_merek = t.ID_merek");
        JRResultSetDataSource resultSetDataSource = new JRResultSetDataSource(rs);
        System.out.println("Filling report...");
        JasperFillManager.fillReportToFile("C:\\Users\\Cheria\\Documents\\NetBeansProjects\\RadhaSanakaraApp\\src\\Pimpinan\\LaporanInventory.jasper", new HashMap(), resultSetDataSource);
        JasperViewer jv = new JasperViewer("C:\\Users\\Cheria\\Documents\\NetBeansProjects\\RadhaSanakaraApp\\src\\Pimpinan\\LaporanInventory.jrprint", false, false);  
        jv.setVisible(true);
        System.out.println("Done!");
        

        rs.close();
        st.close();
        con.close();
        }
                catch(SQLException | JRException e){
                e.printStackTrace();
            }
    }//GEN-LAST:event_btnlapinvActionPerformed

    private void btnbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbsActionPerformed
        // TODO add your handling code here:
        try{
        connect();
        String[] tgl = cbbulan.getSelectedItem().toString().split(" ");
        rs = st.executeQuery("SELECT nama_barang, SUM(jumlah_jual), MONTHNAME(tanggal_jual), YEAR(tanggal_jual) FROM tblpenjualan j, tblinventory i WHERE j.ID_barang = i.ID_barang AND YEAR(now()) = YEAR(tanggal_jual) AND status_penjualan = 'Lunas' AND MONTHNAME(tanggal_jual) = '"+tgl[0]+"' AND YEAR(tanggal_jual) = '"+tgl[1]+"' group by j.ID_barang ORDER BY SUM(jumlah_jual) desc");
        JRResultSetDataSource resultSetDataSource = new JRResultSetDataSource(rs);
        
        System.out.println("Filling report...");
        
        JasperFillManager.fillReportToFile("C:\\Users\\Cheria\\Documents\\NetBeansProjects\\RadhaSanakaraApp\\src\\Pimpinan\\LaporanBestSeller.jasper", new HashMap(), resultSetDataSource);
        
        JasperViewer jv = new JasperViewer("C:\\Users\\Cheria\\Documents\\NetBeansProjects\\RadhaSanakaraApp\\src\\Pimpinan\\LaporanBestSeller.jrprint", false, false);  
        jv.setVisible(true);
        System.out.println("Done!");
        

        rs.close();
        st.close();
        con.close();
        }
                catch(SQLException | JRException e){
                e.printStackTrace();
            }
    }//GEN-LAST:event_btnbsActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbs;
    private javax.swing.JButton btnchange;
    private javax.swing.JButton btnlapbeli;
    private javax.swing.JButton btnlapinv;
    private javax.swing.JButton btnlapjual;
    private javax.swing.JButton btnlapkeu;
    private javax.swing.JButton btnlogout;
    private javax.swing.JComboBox cbbulan;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
