/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administrasi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
/**
 *
 * @author Cheria
 */
public class addinventoryForm extends javax.swing.JFrame {
Connection con;
    Statement st;
    ResultSet rs;
    String idbarang = "";
    String [] tipe, satuan;
    
    /**
     * Creates new form addinventoryForm
     */
    public addinventoryForm() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        setTitle("Tambah Barang");
        connect();
        tampildatatipe();
        tampildatasat();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/radhasankara/icon.png")));
    }   

         public void connect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con =DriverManager.getConnection("jdbc:mysql://localhost:3306/radhasankara","root","");
            st = con.createStatement();
            rs = st.executeQuery("select MAX(ID_barang) from tblinventory");
            while(rs.next()) {
        String idbarlengkap = rs.getString(1);
        
        if(idbarlengkap == null){
            idbarang= String.format("%04d", 1);
            lblbar.setText("BAR-"+idbarang);
        }
        else{
        String[] idbarinc = idbarlengkap.split("-");
        int idbar2 = Integer.parseInt(idbarinc[1]);
        idbar2 = idbar2+1;
        idbarang= String.format("%04d", idbar2);
        lblbar.setText("BAR-"+idbarang);
        }
            }
        }
        catch(ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Connection Failed");
            System.out.println(e.getMessage());
            e.printStackTrace();
            }
        }
         


         public void tampildatatipe(){
         try{
            connect();
            rs = st.executeQuery("SELECT ID_tipe, tipe, jenis, merek FROM tbltipe t, tbljenis j, tblmerek m WHERE ID_tipe NOT IN(SELECT t.ID_tipe FROM tbltipe t, tblinventory i WHERE t.ID_tipe = i.ID_tipe) AND j.ID_jenis = t.ID_jenis AND m.ID_merek = t.ID_merek");
           cbtipe.removeAllItems();
            while(rs.next()){
            cbtipe.addItem(rs.getString(3)+" "+rs.getString(4)+" "+rs.getString(2) + "/" +rs.getString(1));
            }
             }
            catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error tip");
            System.out.println(e.getMessage());
            e.printStackTrace();
        }
         }

            
         public void tampildatasat(){
             try{
            connect();
            rs = st.executeQuery("select ID_satuan, satuan from tblsatuan");
            cbsatuan.removeAllItems();
            while(rs.next()){
            cbsatuan.addItem(rs.getString(2) + "/" +rs.getString(1));
            }
            
             }
             catch (Exception e) {
                 System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null,"Error sat");    
            e.printStackTrace();
        }
         }
             
                     
         
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtbarang = new javax.swing.JTextField();
        cbtipe = new javax.swing.JComboBox();
        cbsatuan = new javax.swing.JComboBox();
        btnok = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblbar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Cambria", 3, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Radha Sankara");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nama Barang");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Tipe");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Satuan");

        txtbarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbarangActionPerformed(evt);
            }
        });

        cbtipe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbtipe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbtipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtipeActionPerformed(evt);
            }
        });

        cbsatuan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbsatuan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbsatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsatuanActionPerformed(evt);
            }
        });

        btnok.setBackground(new java.awt.Color(0, 150, 0));
        btnok.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnok.setForeground(new java.awt.Color(255, 255, 255));
        btnok.setText("OK");
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });

        btncancel.setBackground(new java.awt.Color(198, 0, 0));
        btncancel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btncancel.setForeground(new java.awt.Color(255, 255, 255));
        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("ID Barang");

        lblbar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbsatuan, 0, 276, Short.MAX_VALUE)
                    .addComponent(cbtipe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtbarang)
                    .addComponent(lblbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(btnok, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblbar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtbarang))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbtipe, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbsatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnok, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
        // TODO add your handling code here:
        try{
            connect();
            String namabar = txtbarang.getText();
            tipe = cbtipe.getSelectedItem().toString().split("/"); 
            satuan = cbsatuan.getSelectedItem().toString().split("/");
            
            st.executeUpdate("insert into tblinventory values('BAR-"+idbarang+"','"+namabar+"','"+tipe[1]+"','"+satuan[1]+"',0,'Available')");
            JOptionPane.showMessageDialog(this,"Data barang berhasil disimpan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            dispose();
            inventoryForm inventoryform = new inventoryForm();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data barang gagal disimpan, silahkan coba lagi!", "Gagal", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            
        }
    }//GEN-LAST:event_btnokActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        dispose();
        inventoryForm inventoryform = new inventoryForm();
    }//GEN-LAST:event_btncancelActionPerformed

    private void cbtipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbtipeActionPerformed

    private void cbsatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsatuanActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbsatuanActionPerformed

    private void txtbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbarangActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnok;
    private javax.swing.JComboBox cbsatuan;
    private javax.swing.JComboBox cbtipe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblbar;
    private javax.swing.JTextField txtbarang;
    // End of variables declaration//GEN-END:variables
}
