/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administrasi;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Cheria
 */
public class customersdataForm extends javax.swing.JFrame {
    Connection con;
    Statement st;
    ResultSet rs;
    /**
     * Creates new form customersdataForm
     */
    public customersdataForm() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        setVisible(true);
        setTitle("Data Customers");
        connect();
        tampildata();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/radhasankara/icon.png")));
    }
    
    public void connect() {
        try {
        Class.forName("com.mysql.jdbc.Driver");
        con =DriverManager.getConnection("jdbc:mysql://localhost:3306/radhasankara","root","");
        st = con.createStatement();
        }
        catch(ClassNotFoundException | SQLException e) {
        JOptionPane.showMessageDialog(null, "Connection Failed");
        System.out.println(e.getMessage());
        }
    }
    
    public void tampildata() {
        DefaultTableModel tbl1 = new DefaultTableModel();
        tbl1.addColumn("ID Customer");
        tbl1.addColumn("Nama Customers");
        tbl1.addColumn("Alamat");
        tbl1.addColumn("Kelurahan");
        tbl1.addColumn("Kecamatan");
        tbl1.addColumn("Kota");
        tbl1.addColumn("Kode Pos");
        tbl1.addColumn("Nomor Telepon");
        tbl1.addColumn("Email");
        tbl1.addColumn("Tipe Customer");
        try{
            connect();
            String sql= "select * from tblcustomers";
            rs = st.executeQuery(sql);
            while (rs.next()) {
                tbl1.addRow(new Object[] {
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                    rs.getString(7),
                    rs.getString(8),
                    rs.getString(9),
                    rs.getString(10)
                });
            }
            tblcustomer.setModel(tbl1);
            
        tblcustomer.getColumnModel().getColumn(0).setPreferredWidth(10);
        tblcustomer.getColumnModel().getColumn(1).setPreferredWidth(100);
        tblcustomer.getColumnModel().getColumn(2).setPreferredWidth(150);
        tblcustomer.getColumnModel().getColumn(3).setPreferredWidth(20);
        tblcustomer.getColumnModel().getColumn(4).setPreferredWidth(20);
        tblcustomer.getColumnModel().getColumn(5).setPreferredWidth(20);
        tblcustomer.getColumnModel().getColumn(6).setPreferredWidth(10);
        tblcustomer.getColumnModel().getColumn(7).setPreferredWidth(50);
        tblcustomer.getColumnModel().getColumn(8).setPreferredWidth(100);
        tblcustomer.getColumnModel().getColumn(9).setPreferredWidth(20);
        
        
        tblcustomer.getColumnModel().getColumn(0).setResizable(false);
        tblcustomer.getColumnModel().getColumn(1).setResizable(false);
        tblcustomer.getColumnModel().getColumn(2).setResizable(false);
        tblcustomer.getColumnModel().getColumn(3).setResizable(false);
        tblcustomer.getColumnModel().getColumn(4).setResizable(false);
        tblcustomer.getColumnModel().getColumn(5).setResizable(false);
        tblcustomer.getColumnModel().getColumn(6).setResizable(false);
        tblcustomer.getColumnModel().getColumn(7).setResizable(false);
        tblcustomer.getColumnModel().getColumn(8).setResizable(false);
        tblcustomer.getColumnModel().getColumn(9).setResizable(false);

        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Ada Kesalahan");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcustomer = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Cambria", 3, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Radha Sankara");

        tblcustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Customer", "Nama Customers", "Alamat", "Kelurahan", "Kecamatan", "Kota", "Kode Pos", "Nomor Telepon", "Email", "Tipe Customer"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblcustomer.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblcustomer);
        if (tblcustomer.getColumnModel().getColumnCount() > 0) {
            tblcustomer.getColumnModel().getColumn(0).setResizable(false);
            tblcustomer.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblcustomer.getColumnModel().getColumn(1).setResizable(false);
            tblcustomer.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblcustomer.getColumnModel().getColumn(2).setResizable(false);
            tblcustomer.getColumnModel().getColumn(2).setPreferredWidth(200);
            tblcustomer.getColumnModel().getColumn(3).setResizable(false);
            tblcustomer.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblcustomer.getColumnModel().getColumn(4).setResizable(false);
            tblcustomer.getColumnModel().getColumn(4).setPreferredWidth(100);
            tblcustomer.getColumnModel().getColumn(5).setResizable(false);
            tblcustomer.getColumnModel().getColumn(5).setPreferredWidth(100);
            tblcustomer.getColumnModel().getColumn(6).setResizable(false);
            tblcustomer.getColumnModel().getColumn(6).setPreferredWidth(100);
            tblcustomer.getColumnModel().getColumn(7).setResizable(false);
            tblcustomer.getColumnModel().getColumn(7).setPreferredWidth(100);
            tblcustomer.getColumnModel().getColumn(8).setResizable(false);
            tblcustomer.getColumnModel().getColumn(8).setPreferredWidth(200);
            tblcustomer.getColumnModel().getColumn(9).setResizable(false);
            tblcustomer.getColumnModel().getColumn(9).setPreferredWidth(100);
        }

        btnAdd.setBackground(new java.awt.Color(0, 150, 0));
        btnAdd.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(206, 113, 12));
        btnUpdate.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(413, 413, 413))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        addcustomerForm add = new addcustomerForm();
        dispose();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        int sel = tblcustomer.getSelectedRow();
        String ID = tblcustomer.getValueAt(sel, 0).toString();
        updatecustomerForm update = new updatecustomerForm();
        update.setID(ID);
        dispose();
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblcustomer;
    // End of variables declaration//GEN-END:variables
}
